config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins

  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pins
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy]
	def index
		@pins =Pin.all.order("created_at DESC" )
	end


	def show
	end

	def new
	@pin = current_user.pins.build
	end

	def create
	@pin = current_user.pins.build(pin_params)
	if @pin.save
		redirect_to @pin, notice: "Successfuly created Pin."
	else
		render 'new'
	end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was Successfuly upadted."
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end


	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Pin Board", root_path %>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "New Pin", new_pin_path %>
          </li>
          <li>
            <%= link_to "Account", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
</body>

</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@pin.errors.count, "error") %>
        prevented this Pin from saving
      </h2>
      <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
    <%= f.input :image, input_html: { class: 'form-control' } %>
  </div>
   <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pins/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">

				<h1>Edit Pin</h1>
			</div>
			<div class="panel-body">
		<%= image_tag @pin.image.url(:medium)%>
				<%= render 'form'%>
				<%= link_to 'back', @pin%>
			</div>
		</div>
	</div>
</div>

app/views/pins/index.html.erb
<% @pins.each do |pin| %>
<div class="col-md-4">
<%= link_to (image_tag pin.image.url(:medium)), pin %>
<h1><%= link_to pin.title, pin%></h1>
<p>Submitted by
	<%= pin.user.email%></p>
	</div>
<% end %>

app/views/pins/new.html.erb
<%#= link_to "back", root_path %>

<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Create A New Pin</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
              Submitted by
              <%= @pin.user.email %>
            </p>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
                <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>